[package]
name = "lapinou"
version = "0.1.3"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with smol"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapinou"
keywords = ["amqp", "rabbitmq", "mio", "futures", "smol"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default"]

[dependencies]
simple-mutex = "^1.0"
smol = "^0.1.18"

[dependencies.lapin]
version = "^1.2"
path = ".."
default-features = false

[dev-dependencies]
env_logger = "^0.7"
futures-util = "^0.3"
log = "^0.4"
