[package]
name = "async-amqp"
version = "0.1.3"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with async-std"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/tokio-amqp"
keywords = ["amqp", "async-std", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default"]

[dependencies.async-std]
version = "^1.6.2"
features = ["default"]

[dependencies.lapin]
version = "^1.2"
path = ".."
default-features = false

[dependencies.lapinou]
version = "^0.1.3"
path = "../lapinou"
default-features = false

[dev-dependencies]
env_logger = "^0.7"
log = "^0.4"

[dev-dependencies.async-std]
version = "^1.6.2"
features = ["attributes", "default", "unstable"]
